# Site settings
title: GIS blog
description: "GIS blog"
url: ""
author:
  name: "Max Kliver"
  email: "dh0m0ch@gmail.com"
  url: ""

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

plugins:
  - jekyll-sitemap
# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
